### ISSUE TITLE
Encountering Rare Deadlock

### ISSUE THREAD

**Issue by Skylion007** [nagadomi/animeface-2009#4]
First of all, excellent job on the repository. I am getting much better results than with other libraries. I do however noticed that when I am processing a large number of files I will occasionally get deadlocks. (On the order of 10,000+). I do not have much experience debugging OpenMP code, but if you let me know any information you need to help track down the bug let me know, and I'll analyze it. You might want to consider using an automated tool like Helgrind to help remove the deadlocks. That being said, whatever race condition that is causing the deadlock is relatively rare. I have compiled with default settings from the build script on Ubuntu 16.04. 

The bug was encountered when running face_collector.rb

**Comment by nagadomi** [comment]
This code uses only `omp parallel for` syntax with OpneMP, so I think it should be no deadlock problem. But most of code of this is written by C, it might be a memory related issue.
I fixed one of issue that is overlapping memcpy. (https://github.com/nagadomi/animeface-2009/commit/b78f9cd2799af82f753e21a3c45c6c1f317b707f)
In additionally, ImageMagick+libpng in Ubuntu 16.04 may crash when loading a PNG image containing more than 8 MB chunks (large metadata).

And you can check where the code is stopped with `gdb`.

1. Add `-g0` option to `nvxs/configure.ac` (around line 36).
```
CFLAGS+=" -g0 "
```

2.  Rebuild
```
cd nvxs
./autogen.sh
cd ..
./build.sh
```

3. Run with gdb.
```
$ cd animeface-ruby
$ gdb --args ruby face_collector.rb --src src --dest dest 
(gdb) run
....
.... ( When deadlock occurs, you can stop with CTRL+C, and display the backtrace with `bt` )
^C
(gdb) bt 
```

**Comment by Skylion007** [comment]
Actually upon further examination, it doesn't appear to be a deadlock based on the process status code. It might be a live lock though. I'll pull the changes and see if I continue to run into the issue.

**Comment by Skylion007** [comment]
While it is rare, I was unfortunately able to reproduce it again. :( Took 76000 images for it to freeze. Also seems  to happen more often when the system is under high load.

**Comment by Skylion007** [comment]
@nagadomi I noticed the old releases of NVXS on your website still have the bug from commit b78f9cd is still in the source code of NVXS from your website. I noticed this when I was trying to build [Python bindings](https://github.com/nya3jp/python-animeface/blob/master/README.md) for this project. You might want to update the source there too.

**Comment by nagadomi** [comment]
hmm, I will remove that source code from the website and link to this git repo.
Note that I changed the interface of `nv_animeface_detect` https://github.com/nagadomi/animeface-2009/commit/a01c02c867c66f63b934e2a3add68e06e32242de so need to fix that python bindings.
